import type { ActionCard } from './types';

/**
 * 30 cartes « action du jour » (modèle de droite).
 *
 * Le titre s'affiche après « Aujourd'hui : ».
 * Pour ajouter / modifier une carte : copie un bloc { ... } et change les textes.
 */
const a = (card: Omit<ActionCard, 'kind'>): ActionCard => ({ kind: 'action', ...card });

export const ACTIONS: ActionCard[] = [
    a({
        id: 'nature-sans-telephone',
        title: '20 minutes dans la nature sans téléphone.',
        category: 'nature',
        why: 'Se reconnecter à la nature permet de ralentir, d’apaiser le mental et de retrouver de l’énergie en douceur.',
        mantra: 'Je me reconnecte à l’essentiel, ici et maintenant.',
        tip: 'Marche lentement, observe ce qui t’entoure, écoute les sons, ressens l’air sur ta peau. Pas besoin d’aller loin : un parc, un jardin ou même quelques arbres suffisent.',
    }),
    a({
        id: 'verre-eau',
        title: 'un grand verre d’eau toutes les deux heures.',
        category: 'eau',
        why: 'Bien s’hydrater aide à garder de l’énergie et de la concentration tout au long de la journée.',
        mantra: 'Je prends soin de moi, gorgée après gorgée.',
        tip: 'Pose une carafe ou une gourde bien en vue. Ajoute une rondelle de citron, de concombre ou quelques feuilles de menthe pour le plaisir.',
    }),
    a({
        id: 'message-gratitude',
        title: 'un message de gratitude à quelqu’un.',
        category: 'lien',
        why: 'Exprimer sa reconnaissance renforce les liens, et fait autant de bien à la personne qui donne qu’à celle qui reçoit.',
        mantra: 'Ma gratitude illumine ma journée et celle des autres.',
        tip: 'Donne un détail concret : ce que la personne a fait et en quoi cela a compté pour toi. Quelques lignes sincères suffisent.',
    }),
    a({
        id: 'ecrans-avant-dormir',
        title: 'pas d’écran une heure avant de dormir.',
        category: 'cocon',
        why: 'La lumière et les sollicitations des écrans gardent l’esprit en éveil. Une heure sans écran aide à préparer un sommeil plus paisible.',
        mantra: 'Le soir, je ralentis et je m’offre du repos.',
        tip: 'Mets ton téléphone en charge hors de ta chambre et remplace-le par un livre, une tisane, quelques étirements ou une discussion.',
    }),
    a({
        id: 'marche-30',
        title: '30 minutes de marche, à ton rythme.',
        category: 'mouvement',
        why: 'Marcher fait du bien au corps comme au moral : on se dégourdit les jambes, on aère l’esprit et on relâche les tensions.',
        mantra: 'À chaque pas, je gagne en légèreté.',
        tip: 'Descends un arrêt plus tôt, marche pendant un appel ou fais le tour du quartier après le repas. Trois fois 10 minutes, ça compte aussi !',
    }),
    a({
        id: 'repas-sans-ecran',
        title: 'un repas sans écran, en pleine conscience.',
        category: 'meditation',
        why: 'Manger sans distraction permet de mieux savourer, de mieux écouter sa faim et de faire une vraie pause dans la journée.',
        mantra: 'Je savoure chaque bouchée, je nourris mon corps et mon esprit.',
        tip: 'Laisse ton téléphone dans une autre pièce. Prends les 3 premières bouchées très lentement, en observant les saveurs, les textures et les couleurs.',
    }),
    a({
        id: 'trois-bonheurs',
        title: '3 petits bonheurs à noter ce soir.',
        category: 'cocon',
        why: 'Prendre l’habitude de remarquer ce qui va bien entraîne le regard vers le positif, jour après jour.',
        mantra: 'Ma journée est pleine de petites merveilles.',
        tip: 'Garde un carnet sur ta table de nuit. Un rayon de soleil, un sourire, un bon café : les petits bonheurs sont les plus précieux.',
    }),
    a({
        id: 'etirements-reveil',
        title: '5 minutes d’étirements au réveil.',
        category: 'mouvement',
        why: 'S’étirer le matin réveille le corps en douceur, délie les articulations et donne un bel élan pour la journée.',
        mantra: 'Je m’étire vers une belle journée.',
        tip: 'Avant même de te lever, étire-toi dans ton lit comme un chat : bras au-dessus de la tête, pointes de pieds tendues. Puis bâille sans retenue !',
    }),
    a({
        id: 'danser',
        title: 'danser sur ta chanson préférée.',
        category: 'mouvement',
        why: 'Danser libère de l’énergie, fait sourire et chasse les tensions en quelques minutes seulement.',
        mantra: 'Je laisse la joie mettre mon corps en mouvement.',
        tip: 'Monte le son, ferme la porte si tu veux, et bouge comme si personne ne te regardait. Une seule chanson suffit pour changer d’humeur.',
    }),
    a({
        id: 'infusion',
        title: 'une infusion savourée en pleine conscience.',
        category: 'cocon',
        why: 'Prendre le temps de préparer et de boire une boisson chaude crée une vraie pause, un petit rituel de douceur.',
        mantra: 'Je m’accorde une pause, rien que pour moi.',
        tip: 'Réchauffe tes mains autour de la tasse, respire le parfum, bois à petites gorgées. Pas de téléphone : juste toi et ta tasse.',
    }),
    a({
        id: 'ranger-petit-espace',
        title: 'ranger un seul petit espace.',
        category: 'cocon',
        why: 'Un espace dégagé apporte une sensation de légèreté et de clarté. Commencer petit rend la chose facile et satisfaisante.',
        mantra: 'Je fais de la place pour ce qui compte.',
        tip: 'Choisis un tiroir, une étagère ou ton sac. Mets un minuteur de 10 minutes et arrête-toi quand il sonne : le plus dur, c’est de commencer.',
    }),
    a({
        id: 'appeler',
        title: 'appeler une personne que tu aimes.',
        category: 'lien',
        why: 'Entendre une voix chère crée plus de lien qu’un message. Un simple appel peut illuminer deux journées.',
        mantra: 'Je nourris les liens qui me font du bien.',
        tip: 'Pas besoin de raison : « Je pensais à toi » suffit. Même 5 minutes au téléphone, ça compte.',
    }),
    a({
        id: 'trois-pauses',
        title: '3 vraies pauses de 5 minutes.',
        category: 'souffle',
        why: 'De courtes pauses régulières aident à préserver son énergie et sa concentration, et évitent le coup de fatigue de fin de journée.',
        mantra: 'Je m’arrête un instant pour mieux repartir.',
        tip: 'Programme 3 alarmes discrètes. À chaque sonnerie : lève-toi, étire-toi, regarde au loin par la fenêtre et prends 5 grandes respirations.',
    }),
    a({
        id: 'compliment',
        title: 'un compliment sincère à quelqu’un.',
        category: 'lien',
        why: 'Un compliment sincère fait du bien à la personne qui le reçoit… et à celle qui le fait. Un petit cadeau qui ne coûte rien.',
        mantra: 'Je vois le beau chez les autres et je le leur dis.',
        tip: 'Complimente une qualité ou un effort plutôt qu’une apparence : « J’admire ta patience », « Merci pour ton aide ».',
    }),
    a({
        id: 'coucher-tot',
        title: 'au lit 30 minutes plus tôt ce soir.',
        category: 'cocon',
        why: 'Le sommeil est l’un des piliers du bien-être. Une petite demi-heure de plus peut faire une vraie différence le lendemain.',
        mantra: 'Je m’offre le repos que je mérite.',
        tip: 'Mets une alarme « heure du coucher » sur ton téléphone. Tamise les lumières et prépare ta chambre : fraîche, calme et sombre.',
    }),
    a({
        id: 'regarder-ciel',
        title: '5 minutes à regarder le ciel.',
        category: 'nature',
        why: 'Lever les yeux vers le ciel aide à prendre du recul, à respirer plus amplement et à relativiser ce qui nous préoccupe.',
        mantra: 'Je suis une petite part d’un grand tout.',
        tip: 'Observe les nuages, leurs formes, leur vitesse, les couleurs qui changent. Le soir, cherche la première étoile.',
    }),
    a({
        id: 'escalier',
        title: 'l’escalier plutôt que l’ascenseur.',
        category: 'mouvement',
        why: 'Chaque petit mouvement du quotidien compte. Bouger réveille le corps et chasse la fatigue de la position assise.',
        mantra: 'Mon corps aime bouger, je lui offre du mouvement.',
        tip: 'Monte à ton rythme, sans te presser. Et toutes les heures, lève-toi quelques instants pour marcher ou t’étirer.',
    }),
    a({
        id: 'assiette-coloree',
        title: 'une assiette pleine de couleurs.',
        category: 'nature',
        why: 'Varier les couleurs dans son assiette, c’est varier les fruits et légumes, et se faire plaisir avec les yeux comme avec le palais.',
        mantra: 'Je nourris mon corps avec plaisir et gratitude.',
        tip: 'Vise 3 couleurs différentes dans ton repas : des tomates, des carottes, des épinards, une poignée de fruits rouges… Laisse parler ta créativité.',
    }),
    a({
        id: 'dire-non',
        title: 'dire non à une chose qui ne te convient pas.',
        category: 'accompagnement',
        why: 'Savoir dire non, c’est respecter ses limites et son énergie. Chaque « non » juste est un « oui » à soi-même.',
        mantra: 'Je respecte mes limites avec douceur et fermeté.',
        tip: 'Une phrase simple et bienveillante suffit : « Merci d’avoir pensé à moi, mais cette fois je ne pourrai pas. » Pas besoin de te justifier longuement.',
    }),
    a({
        id: 'sans-notifications',
        title: 'deux heures sans notifications.',
        category: 'cocon',
        why: 'Les notifications morcellent l’attention. S’en libérer quelques heures permet de se concentrer et de retrouver du calme.',
        mantra: 'Je choisis où va mon attention.',
        tip: 'Active le mode « Ne pas déranger » ou « Concentration ». Préviens tes proches si besoin : ce qui est vraiment urgent trouvera toujours un chemin.',
    }),
    a({
        id: 'lire',
        title: '15 pages d’un livre qui te fait envie.',
        category: 'cocon',
        why: 'Lire transporte ailleurs, apaise l’esprit et offre une vraie pause loin des écrans.',
        mantra: 'Je m’évade, page après page.',
        tip: 'Garde un livre toujours à portée de main : dans ton sac, sur ta table de nuit. Les transports ou la pause déjeuner deviennent des moments d’évasion.',
    }),
    a({
        id: 'geste-gentil',
        title: 'un geste gentil, sans rien attendre en retour.',
        category: 'lien',
        why: 'Les gestes de gentillesse créent un cercle vertueux : ils font du bien aux autres et nourrissent notre propre joie.',
        mantra: 'Ma gentillesse rend le monde un peu plus doux.',
        tip: 'Tiens une porte, laisse passer quelqu’un, apporte un café à un collègue, glisse un mot doux… Les petits gestes comptent.',
    }),
    a({
        id: 'douche-consciente',
        title: 'une douche en pleine conscience.',
        category: 'eau',
        why: 'Transformer un geste du quotidien en moment de présence est une façon simple de méditer, sans prendre de temps en plus.',
        mantra: 'L’eau emporte ce dont je n’ai plus besoin.',
        tip: 'Sens la température de l’eau, le bruit des gouttes, le parfum du savon. Imagine que l’eau emporte avec elle la fatigue et les soucis.',
    }),
    a({
        id: 'musique-yeux-fermes',
        title: 'un morceau de musique, les yeux fermés.',
        category: 'cocon',
        why: 'Écouter vraiment la musique, sans rien faire d’autre, offre un moment de détente et d’émotion accessible à tout moment.',
        mantra: 'Je m’accorde au rythme qui me fait du bien.',
        tip: 'Mets tes écouteurs, choisis un morceau que tu aimes et ferme les yeux. Essaie d’entendre un détail que tu n’avais jamais remarqué.',
    }),
    a({
        id: 'fenetre-ouverte',
        title: '3 minutes à la fenêtre ouverte.',
        category: 'souffle',
        why: 'Respirer de l’air frais réveille le corps, aère l’esprit et renouvelle l’air de la maison.',
        mantra: 'J’accueille cette nouvelle journée à pleins poumons.',
        tip: 'Ouvre grand la fenêtre, pose tes mains sur le rebord et prends 5 grandes respirations. Écoute les bruits du dehors.',
    }),
    a({
        id: 'creer',
        title: '15 minutes pour créer quelque chose.',
        category: 'cocon',
        why: 'Créer (dessiner, écrire, cuisiner, bricoler) apaise l’esprit et apporte la satisfaction d’avoir fait quelque chose de ses mains.',
        mantra: 'Je laisse ma créativité s’exprimer librement.',
        tip: 'Aucun talent requis : un gribouillage, un poème, une recette improvisée… Le plaisir de faire compte plus que le résultat.',
    }),
    a({
        id: 'rire',
        title: 'une bonne dose de rire.',
        category: 'lien',
        why: 'Rire détend, rapproche des autres et remet de la légèreté dans la journée.',
        mantra: 'Je laisse le rire alléger mon cœur.',
        tip: 'Regarde une vidéo drôle, appelle la personne qui te fait toujours rire ou repense à un souvenir amusant. Le rire est contagieux : partage-le !',
    }),
    a({
        id: 'se-feliciter',
        title: 'te féliciter pour une réussite, même petite.',
        category: 'accompagnement',
        why: 'On remarque souvent ce qui ne va pas, et trop rarement ce qu’on réussit. Célébrer ses victoires nourrit la confiance en soi.',
        mantra: 'Je reconnais chacun de mes pas en avant.',
        tip: 'Écris ta réussite du jour et dis-toi « Bravo » à voix haute. Tu peux même t’offrir une petite récompense.',
    }),
    a({
        id: 'pieds-nus',
        title: 'quelques minutes pieds nus.',
        category: 'nature',
        why: 'Marcher pieds nus réveille les sensations, masse la plante des pieds et aide à revenir dans le moment présent.',
        mantra: 'Je sens la terre qui me porte.',
        tip: 'Sur l’herbe, le sable, un tapis ou même le parquet : ressens chaque texture sous tes pieds. Marche lentement, en conscience.',
    }),
    a({
        id: 'rien-faire',
        title: '10 minutes à ne rien faire.',
        category: 'cocon',
        why: 'Ne rien faire, c’est laisser l’esprit se reposer et vagabonder. C’est souvent dans ces moments que naissent les meilleures idées.',
        mantra: 'J’ai le droit de simplement être.',
        tip: 'Assieds-toi près d’une fenêtre, sans téléphone ni objectif. Si l’ennui arrive, accueille-le : c’est le début de la détente.',
    }),
];
