import type { PracticeCard } from './types';

const p = (card: Omit<PracticeCard, 'kind'>): PracticeCard => ({ kind: 'pratique', ...card });

export const PRACTICES: PracticeCard[] = [
    p({ id: 'sejours-egypte', name: 'Séjours immersifs Égypte', withArticle: 'les séjours immersifs en Égypte', category: 'accompagnement', what: 'Une expérience immersive en Égypte pour se reconnecter à soi.', mantra: 'Je me reconnecte à mon essence en voyageant.', exercise: 'Prends 10 minutes pour visualiser un voyage qui te fait rêver.' }),
    p({ id: 'bioenergetic', name: 'Bioénergétique', withArticle: 'la bioénergétique', category: 'accompagnement', what: 'Médecine traditionnelle chinoise et physique quantique pour explorer ton potentiel.', mantra: 'Mon énergie circule librement.', exercise: 'Respire profondément et sens l\'énergie circuler dans tout ton corps.' }),
    p({ id: 'communication', name: 'Communication', withArticle: 'la communication', category: 'accompagnement', what: 'L\'art de communiquer avec clarté et empathie.', mantra: 'Je m\'exprime avec authenticité.', exercise: 'Exprime-toi sincèrement avec quelqu\'un proche.' }),
    p({ id: 'photographie-holistique', name: 'Photographie holistique', withArticle: 'la photographie holistique', category: 'soin', what: 'Capture l\'essence du moment pour mieux te voir.', mantra: 'Je suis belle, à travers les yeux de l\'amour.', exercise: 'Prends une photo de toi dans un moment de présence.' }),
    p({ id: 'sophrologie-burnout', name: 'Sophrologie - Burn-out', withArticle: 'la sophrologie pour le burn-out', category: 'souffle', what: 'Sophrologie spécialisée dans l\'accompagnement du burn-out.', mantra: 'Je reprends mon souffle et mes forces.', exercise: 'Pratique 3 respirations conscientes dès que tu ressens de la fatigue.' }),
    p({ id: 'massage-relaxation', name: 'Massage et relaxation', withArticle: 'le massage et la relaxation', category: 'soin', what: 'Un toucher bienveillant pour détendre corps et esprit.', mantra: 'Je me détends et je me fais du bien.', exercise: 'Masse tes temples doucement pendant 2 minutes.' }),
    p({ id: 'head-spa', name: 'Head spa Japonais', withArticle: 'le head spa japonais', category: 'soin', what: 'Un massage de la tête inspiré des traditions japonaises.', mantra: 'Mon esprit se libère, mon cœur s\'apaise.', exercise: 'Masse délicatement ton cuir chevelu avec les pulpe de tes doigts.' }),
    p({ id: 'nutrition', name: 'Coach en nutrition', withArticle: 'le coaching en nutrition', category: 'accompagnement', what: 'Un accompagnement pour une nutrition consciente et alignée.', mantra: 'Je nourris mon corps avec gratitude.', exercise: 'Prends ta prochaine repas en pleine conscience.' }),
    p({ id: 'coaching-entrepreneurial', name: 'Coaching entrepreneurial', withArticle: 'le coaching entrepreneurial', category: 'accompagnement', what: 'Un soutien pour développer tes projets avec confiance.', mantra: 'Je construis mon avenir avec audace.', exercise: 'Écris 3 actions concrètes pour ton projet.' }),
    p({ id: 'psychopraticien', name: 'Psychopraticien - Art-thérapeute', withArticle: 'le psychopraticien art-thérapeute', category: 'accompagnement', what: 'Accompagnement par l\'art pour explorer tes émotions.', mantra: 'L\'art me libère et m\'exprime.', exercise: 'Crée quelque chose sans jugement, juste pour toi.' }),
    p({ id: 'reflexologie', name: 'Réflexologie', withArticle: 'la réflexologie', category: 'soin', what: 'Un travail sur les zones réflexes pour harmoniser le corps.', mantra: 'Chaque point en moi trouve son équilibre.', exercise: 'Masse tes pieds avec intention et bienveillance.' }),
    p({ id: 'bien-etre-beaute', name: 'Accompagnante bien-être & beauté', withArticle: 'l\'accompagnante bien-être et beauté', category: 'soin', what: 'Un soutien holistique pour ta beauté et ton bien-être.', mantra: 'Je suis belle, naturellement et profondément.', exercise: 'Prends soin de toi comme tu le ferais pour quelqu\'un d\'aimé.' }),
    p({ id: 'naturopathie', name: 'Naturopathie', withArticle: 'la naturopathie', category: 'accompagnement', what: 'Une approche naturelle pour retrouver l\'équilibre.', mantra: 'La nature me guérit et m\'inspire.', exercise: 'Consomme un aliment naturel en mindfulness.' }),
    p({ id: 'psychogenealogie', name: 'Psychogénéalogie - Coaching couple', withArticle: 'la psychogénéalogie et le coaching de couple', category: 'accompagnement', what: 'Explorer les schémas familiaux pour libérer tes relations.', mantra: 'Je guéris mes racines pour grandir librement.', exercise: 'Réfléchis à un schéma familial que tu souhaites transformer.' }),
    p({ id: 'massage-beaute', name: 'Massage beauté', withArticle: 'le massage beauté', category: 'soin', what: 'Un massage pour illuminer ta peau et ton éclat.', mantra: 'Mon éclat naturel rayonne.', exercise: 'Massage ton visage avec des mouvements ascendants.' }),
    p({ id: 'hypnose', name: 'Hypnose', withArticle: 'l\'hypnose', category: 'accompagnement', what: 'Un état de conscience modifiée pour accéder à ton potentiel.', mantra: 'Je suis connectée à ma sagesse intérieure.', exercise: 'Détends-toi et observe le flux de ta respiration.' }),
    p({ id: 'reiki', name: 'Reiki', withArticle: 'le reiki', category: 'soin', what: 'Une énergie de guérison transmise par les mains.', mantra: 'Je suis canal de lumière et d\'amour.', exercise: 'Pose tes mains sur ton cœur et ressens la chaleur.' }),
    p({ id: 'coaching-vie', name: 'Coaching de vie', withArticle: 'le coaching de vie', category: 'accompagnement', what: 'Un soutien pour créer la vie que tu souhaites vraiment.', mantra: 'Je crée ma vie avec intention.', exercise: 'Définis une intention claire pour ce mois.' }),
    p({ id: 'meditation', name: 'Méditation', withArticle: 'la méditation', category: 'meditation', what: 'Un retour à toi-même à travers la présence.', mantra: 'Je suis ici, maintenant, en paix.', exercise: 'Médite pendant 5 minutes en silence.' }),
];
