import type { PracticeCard } from './types';

/**
 * 100 cartes « pratique » (modèle de gauche).
 *
 * Pour ajouter / modifier une carte : copie un bloc { ... } et change les textes.
 * Chaque `id` doit être unique. Champs facultatifs : hook, url, image.
 */
const p = (card: Omit<PracticeCard, 'kind'>): PracticeCard => ({ kind: 'pratique', ...card });

export const PRACTICES: PracticeCard[] = [
    // ───────────── Souffle & relaxation ─────────────
    p({
        id: 'sophrologie',
        name: 'Sophrologie',
        withArticle: 'la sophrologie',
        category: 'souffle',
        what: 'Une pratique associant notamment respiration, relaxation et visualisation, proposée dans une démarche de mieux-être.',
        mantra: 'Je prends le temps de respirer, et tout devient plus clair.',
        exercise: 'Assieds-toi confortablement, ferme les yeux et prends 3 grandes respirations lentes. À chaque inspiration, répète mentalement : « Je me calme ». À chaque expiration : « Je me libère ».',
    }),
    p({
        id: 'coherence-cardiaque',
        name: 'Cohérence cardiaque',
        withArticle: 'la cohérence cardiaque',
        category: 'souffle',
        what: 'Une technique de respiration rythmée, souvent pratiquée autour de 6 respirations par minute, pour retrouver un souffle régulier et apaisé.',
        mantra: 'Mon souffle est calme, mon cœur suit son rythme.',
        exercise: 'Inspire doucement par le nez en comptant jusqu’à 5, puis expire par la bouche en comptant jusqu’à 5. Continue ainsi pendant 3 minutes, sans forcer, en gardant les épaules relâchées.',
    }),
    p({
        id: 'respiration-consciente',
        name: 'Respiration consciente',
        withArticle: 'la respiration consciente',
        category: 'souffle',
        what: 'Une pratique qui consiste à porter son attention sur son souffle, sans chercher à le contrôler, pour revenir à l’instant présent.',
        mantra: 'Chaque respiration me ramène à moi.',
        exercise: 'Pose une main sur ton ventre. Observe simplement l’air qui entre et qui sort, sans le modifier. Chaque fois que ton esprit s’évade, reviens gentiment à la sensation de ta main qui monte et qui descend.',
    }),
    p({
        id: 'pranayama',
        name: 'Pranayama',
        withArticle: 'le pranayama',
        category: 'souffle',
        what: 'L’ensemble des techniques de respiration issues du yoga, qui invitent à explorer l’amplitude et le rythme du souffle.',
        mantra: 'J’inspire l’énergie, j’expire ce qui me pèse.',
        exercise: 'Assieds-toi le dos droit. Inspire par le nez en gonflant d’abord le ventre, puis la poitrine. Expire lentement dans l’ordre inverse. Répète 8 fois, à ton rythme, en allongeant un peu l’expiration.',
    }),
    p({
        id: 'relaxation-progressive',
        name: 'Relaxation progressive',
        withArticle: 'la relaxation progressive',
        category: 'souffle',
        what: 'Une méthode de détente qui alterne contraction et relâchement des groupes musculaires, pour mieux ressentir la différence entre tension et détente.',
        mantra: 'Je relâche, muscle après muscle.',
        exercise: 'Serre les poings 5 secondes, puis relâche complètement. Fais de même avec les épaules (monte-les vers les oreilles), puis avec le visage. Prends le temps de sentir la détente qui s’installe après chaque relâchement.',
    }),
    p({
        id: 'training-autogene',
        name: 'Training autogène',
        withArticle: 'le training autogène',
        category: 'souffle',
        what: 'Une méthode de relaxation par autosuggestion, basée sur des sensations de lourdeur et de chaleur dans le corps.',
        mantra: 'Mon corps est lourd, chaud et détendu.',
        exercise: 'Ferme les yeux et répète lentement : « Mon bras droit est lourd… », puis « Mon bras droit est chaud… ». Fais de même avec le bras gauche, puis les jambes. Laisse venir les sensations, sans rien forcer.',
    }),
    p({
        id: 'methode-vittoz',
        name: 'Méthode Vittoz',
        withArticle: 'la méthode Vittoz',
        category: 'souffle',
        what: 'Une approche psycho-sensorielle qui invite à retrouver l’équilibre entre pensées et sensations, à travers des exercices simples de réceptivité.',
        mantra: 'Je reçois le monde avec tous mes sens.',
        exercise: 'Prends un objet près de toi. Pendant une minute, observe-le vraiment : sa couleur, sa forme, sa texture. Puis ferme les yeux et touche-le. Enfin, écoute les sons autour de toi. Un sens à la fois, en douceur.',
    }),
    p({
        id: 'yoga-nidra',
        name: 'Yoga nidra',
        withArticle: 'le yoga nidra',
        category: 'souffle',
        what: 'Souvent appelé « sommeil yogique », c’est une relaxation guidée, allongée, qui invite à un repos profond tout en restant conscient.',
        mantra: 'Je m’autorise à me reposer profondément.',
        exercise: 'Allonge-toi sur le dos, les bras le long du corps. Promène ton attention sur chaque partie du corps : orteils, pieds, mollets, genoux… jusqu’au sommet du crâne, en nommant mentalement chaque zone.',
    }),
    p({
        id: 'visualisation-positive',
        name: 'Visualisation positive',
        withArticle: 'la visualisation positive',
        category: 'souffle',
        what: 'Une technique qui utilise l’imagination pour se représenter une situation apaisante ou un objectif, et en ressentir les émotions positives.',
        mantra: 'J’imagine le meilleur et je m’en rapproche.',
        exercise: 'Ferme les yeux et imagine un lieu où tu te sens parfaitement bien. Qu’y vois-tu ? Qu’entends-tu ? Quelle est la température ? Reste-y 3 minutes, puis reviens doucement en gardant cette sensation.',
    }),
    p({
        id: 'auto-hypnose',
        name: 'Auto-hypnose',
        withArticle: 'l’auto-hypnose',
        category: 'souffle',
        what: 'Une pratique qui permet d’accéder par soi-même à un état de conscience détendu, propice à la concentration et au lâcher-prise.',
        mantra: 'Je laisse mon esprit se poser en douceur.',
        exercise: 'Fixe un point devant toi. Respire lentement et laisse tes paupières devenir lourdes. Compte à rebours de 10 à 1, en te disant que tu te détends un peu plus à chaque chiffre. À 1, savoure ce calme.',
    }),

    // ───────────── Méditation ─────────────
    p({
        id: 'pleine-conscience',
        name: 'Pleine conscience',
        withArticle: 'la méditation de pleine conscience',
        category: 'meditation',
        what: 'Une pratique qui consiste à porter volontairement son attention sur le moment présent, sans jugement : le souffle, les sensations, les pensées.',
        mantra: 'Ici et maintenant, j’accueille ce qui est.',
        exercise: 'Règle un minuteur sur 3 minutes et observe ta respiration. Quand une pensée arrive, nomme-la « pensée », puis reviens au souffle. Il n’y a ni réussite ni échec : seulement revenir.',
    }),
    p({
        id: 'meditation-guidee',
        name: 'Méditation guidée',
        withArticle: 'la méditation guidée',
        category: 'meditation',
        what: 'Une méditation accompagnée par une voix (enregistrement ou praticien) qui guide pas à pas l’attention et la détente.',
        mantra: 'Je me laisse guider vers le calme.',
        exercise: 'Choisis une courte méditation guidée audio de 3 minutes, mets tes écouteurs et installe-toi confortablement. Ton seul objectif : écouter et suivre la voix.',
    }),
    p({
        id: 'vipassana',
        name: 'Vipassana',
        withArticle: 'la méditation Vipassana',
        category: 'meditation',
        what: 'Une méditation traditionnelle d’observation, qui invite à voir les choses telles qu’elles sont, en observant ses sensations avec équanimité.',
        mantra: 'J’observe sans juger, et tout passe.',
        exercise: 'Porte ton attention sur la zone juste sous tes narines. Ressens l’air frais qui entre et l’air plus tiède qui sort. Reste avec cette sensation subtile pendant 3 minutes.',
    }),
    p({
        id: 'metta',
        name: 'Méditation Metta',
        withArticle: 'la méditation Metta',
        category: 'meditation',
        what: 'Aussi appelée méditation de bienveillance, elle consiste à cultiver des souhaits de bonheur pour soi et pour les autres.',
        mantra: 'Que je sois en paix, que tu sois en paix.',
        exercise: 'Ferme les yeux et répète intérieurement : « Que je sois en paix, que je sois dans la joie. » Pense ensuite à une personne que tu aimes et adresse-lui les mêmes souhaits. Termine en les envoyant au monde entier.',
    }),
    p({
        id: 'body-scan',
        name: 'Body scan',
        withArticle: 'le body scan',
        category: 'meditation',
        what: 'Un balayage attentif du corps, zone par zone, pour reprendre contact avec ses sensations et relâcher les tensions.',
        mantra: 'J’habite mon corps avec douceur.',
        exercise: 'Ferme les yeux. Commence par le sommet de ta tête et descends lentement : front, mâchoire, épaules, bras, ventre, jambes, pieds. Là où tu sens une tension, respire dans cette zone et laisse-la fondre.',
    }),
    p({
        id: 'zazen',
        name: 'Zazen',
        withArticle: 'le zazen',
        category: 'meditation',
        what: 'La méditation assise de la tradition zen, qui met l’accent sur la posture, la respiration et le simple fait d’être là.',
        mantra: 'Je suis là, tout simplement.',
        exercise: 'Assieds-toi le dos droit, le menton légèrement rentré, les mains posées l’une dans l’autre. Garde les yeux mi-clos, le regard posé au sol devant toi. Respire naturellement pendant 3 minutes.',
    }),
    p({
        id: 'marche-meditative',
        name: 'Marche méditative',
        withArticle: 'la marche méditative',
        category: 'meditation',
        what: 'Une méditation en mouvement : on marche lentement, en portant toute son attention sur chaque pas et chaque sensation.',
        mantra: 'Chaque pas me pose un peu plus dans l’instant.',
        exercise: 'Marche très lentement sur quelques mètres. Ressens le talon qui se pose, le pied qui se déroule, le poids qui passe d’une jambe à l’autre. Au bout du chemin, fais demi-tour et recommence.',
    }),
    p({
        id: 'meditation-mantra',
        name: 'Méditation mantra',
        withArticle: 'la méditation avec mantra',
        category: 'meditation',
        what: 'Une méditation qui s’appuie sur la répétition d’un mot ou d’une phrase pour apaiser le flot des pensées.',
        mantra: 'Un mot, un souffle, et le calme revient.',
        exercise: 'Choisis un mot doux : « paix », « calme » ou « merci ». Répète-le intérieurement au rythme de ta respiration pendant 3 minutes. Si ton esprit s’égare, reviens simplement à ton mot.',
    }),
    p({
        id: 'mbsr',
        name: 'MBSR',
        withArticle: 'le MBSR',
        category: 'meditation',
        what: 'Un programme de réduction du stress basé sur la pleine conscience, créé par Jon Kabat-Zinn, qui se suit généralement sur 8 semaines.',
        mantra: 'Je choisis de répondre plutôt que de réagir.',
        exercise: 'Fais « l’espace de respiration » : 1 minute pour observer ce qui est là (pensées, émotions), 1 minute centrée sur le souffle, 1 minute pour élargir ton attention à tout le corps.',
    }),
    p({
        id: 'auto-compassion',
        name: 'Auto-compassion',
        withArticle: 'l’auto-compassion',
        category: 'meditation',
        what: 'Une pratique qui invite à se traiter avec la même gentillesse que celle qu’on offrirait à un ami dans un moment difficile.',
        mantra: 'Je mérite ma propre douceur.',
        exercise: 'Pose une main sur ton cœur. Pense à une difficulté du moment et dis-toi : « C’est un moment difficile. Tout le monde en traverse. Je peux m’offrir de la douceur. » Respire quelques instants avec ces mots.',
    }),
    p({
        id: 'bain-sonore',
        name: 'Bain sonore',
        withArticle: 'le bain sonore',
        category: 'meditation',
        what: 'Un moment de détente où l’on se laisse envelopper par les sons et vibrations d’instruments comme les bols chantants ou les gongs.',
        mantra: 'Je laisse les vibrations me traverser.',
        exercise: 'Allonge-toi et écoute un enregistrement de bols chantants. Suis un son depuis son début jusqu’à sa disparition complète, puis le suivant. Laisse ton corps s’alourdir à chaque vibration.',
    }),

    // ───────────── Soins & toucher ─────────────
    p({
        id: 'reflexologie-plantaire',
        name: 'Réflexologie plantaire',
        withArticle: 'la réflexologie plantaire',
        category: 'soin',
        what: 'Une technique de toucher des pieds, qui s’appuie sur l’idée que certaines zones du pied sont reliées au reste du corps. Proposée dans une démarche de détente.',
        mantra: 'Mes pieds me portent, je prends soin d’eux.',
        exercise: 'Pose un pied sur ton genou. Avec les pouces, masse doucement la voûte plantaire en petits cercles, du talon vers les orteils. Termine en étirant chaque orteil. Change de pied.',
    }),
    p({
        id: 'reflexologie-palmaire',
        name: 'Réflexologie palmaire',
        withArticle: 'la réflexologie palmaire',
        category: 'soin',
        what: 'La cousine de la réflexologie plantaire, appliquée aux mains : un toucher précis et apaisant, facile à pratiquer n’importe où.',
        mantra: 'Mes mains se reposent, mon esprit aussi.',
        exercise: 'Avec le pouce, masse le creux de ta main opposée en petits cercles pendant 1 minute. Puis pince doucement chaque doigt, de la base jusqu’au bout. Change de main.',
    }),
    p({
        id: 'shiatsu',
        name: 'Shiatsu',
        withArticle: 'le shiatsu',
        category: 'soin',
        what: 'Une technique japonaise de pressions avec les doigts et les paumes le long du corps, pratiquée habillé, dans une approche de détente et d’équilibre.',
        mantra: 'Je retrouve mon équilibre, point par point.',
        exercise: 'Du bout des doigts, fais de légères pressions le long de ta nuque, de la base du crâne jusqu’aux épaules. Tiens chaque pression 3 secondes en expirant. Répète 3 fois.',
    }),
    p({
        id: 'massage-californien',
        name: 'Massage californien',
        withArticle: 'le massage californien',
        category: 'soin',
        what: 'Un massage enveloppant aux longs mouvements lents et fluides, qui invite au lâcher-prise et à la détente profonde.',
        mantra: 'Je m’autorise à lâcher prise.',
        exercise: 'Mets un peu de crème sur tes mains et masse tes avant-bras avec de longs gestes lents, du poignet vers le coude. Sens la chaleur de tes mains. Prends ton temps, comme si c’était un cadeau.',
    }),
    p({
        id: 'massage-suedois',
        name: 'Massage suédois',
        withArticle: 'le massage suédois',
        category: 'soin',
        what: 'Un massage plus tonique qui travaille les muscles par pétrissage, frictions et effleurages, apprécié après l’effort ou en cas de tensions.',
        mantra: 'Je dénoue mes tensions une à une.',
        exercise: 'Avec la main opposée, pétris doucement le haut de ton épaule, comme une pâte à pain, pendant 1 minute. Change de côté. Termine en roulant les épaules vers l’arrière 5 fois.',
    }),
    p({
        id: 'abhyanga',
        name: 'Massage ayurvédique',
        withArticle: 'le massage ayurvédique',
        category: 'soin',
        what: 'Appelé abhyanga, c’est un massage à l’huile chaude issu de l’ayurveda, aux gestes rythmés, pensé comme un rituel de bien-être.',
        mantra: 'Je nourris mon corps de douceur.',
        exercise: 'Réchauffe quelques gouttes d’huile végétale entre tes mains. Masse tes pieds par mouvements circulaires, puis remonte le long des mollets. Laisse l’huile pénétrer quelques minutes.',
    }),
    p({
        id: 'lomi-lomi',
        name: 'Lomi-lomi',
        withArticle: 'le lomi-lomi',
        category: 'soin',
        what: 'Un massage traditionnel hawaïen, réalisé notamment avec les avant-bras, en longs mouvements qui évoquent les vagues de l’océan.',
        mantra: 'Je me laisse porter comme une vague.',
        exercise: 'Ferme les yeux et imagine le bruit des vagues. Balance doucement ton buste d’avant en arrière au rythme de ta respiration, pendant 3 minutes, comme sur la houle de l’océan.',
    }),
    p({
        id: 'pierres-chaudes',
        name: 'Pierres chaudes',
        withArticle: 'le massage aux pierres chaudes',
        category: 'soin',
        what: 'Un massage qui utilise des pierres volcaniques chauffées, posées ou glissées sur le corps, pour une sensation de chaleur enveloppante.',
        mantra: 'La chaleur m’apaise et me recentre.',
        exercise: 'Remplis une bouillotte d’eau chaude (pas brûlante) ou frotte vivement tes mains. Pose cette chaleur sur ton ventre ou ta nuque. Respire lentement en sentant la chaleur se diffuser.',
    }),
    p({
        id: 'massage-thai',
        name: 'Massage thaï',
        withArticle: 'le massage thaï',
        category: 'soin',
        what: 'Un massage traditionnel thaïlandais, pratiqué au sol et habillé, qui combine pressions et étirements doux. On le surnomme parfois « yoga passif ».',
        mantra: 'Je m’étire vers plus de légèreté.',
        exercise: 'Debout, entrelace tes doigts et étire les bras vers le ciel en inspirant. Penche-toi doucement à droite en expirant, reviens, puis à gauche. Répète 3 fois de chaque côté, sans forcer.',
    }),
    p({
        id: 'tui-na',
        name: 'Tui na',
        withArticle: 'le tui na',
        category: 'soin',
        what: 'Un massage issu de la tradition chinoise, qui associe pressions, frictions et mobilisations le long des méridiens.',
        mantra: 'L’énergie circule librement en moi.',
        exercise: 'Frotte vivement tes mains l’une contre l’autre, puis frictionne tes bras de haut en bas, tes cuisses et tes flancs. Termine en tapotant doucement le haut de ta poitrine du bout des doigts.',
    }),
    p({
        id: 'kobido',
        name: 'Kobido',
        withArticle: 'le kobido',
        category: 'soin',
        what: 'Un massage traditionnel japonais du visage, aux gestes rapides et précis, souvent pratiqué comme un rituel de beauté et de détente.',
        mantra: 'Mon visage se détend, mon sourire revient.',
        exercise: 'Du bout des doigts, fais de petits cercles sur tes tempes, puis le long de ta mâchoire. Lisse ton front du centre vers l’extérieur. Termine en tapotant doucement tes joues.',
    }),
    p({
        id: 'drainage-lymphatique',
        name: 'Drainage lymphatique',
        withArticle: 'le drainage lymphatique',
        category: 'soin',
        what: 'Une technique de massage très douce et rythmée, qui accompagne la circulation de la lymphe et procure une sensation de légèreté.',
        mantra: 'La légèreté s’installe en moi.',
        exercise: 'Allonge-toi, les jambes surélevées sur un coussin. Avec les mains à plat, effleure tes jambes très lentement, des chevilles vers les genoux, puis des genoux vers le haut des cuisses. Des gestes légers comme une plume.',
    }),
    p({
        id: 'dien-chan',
        name: 'Dien Chan',
        withArticle: 'le Dien Chan',
        category: 'soin',
        what: 'Une méthode vietnamienne de réflexologie faciale, qui stimule des points du visage avec les doigts ou de petits outils.',
        mantra: 'Un geste simple, un grand apaisement.',
        exercise: 'Avec le bout du doigt, masse doucement la zone entre tes sourcils en petits cercles pendant 30 secondes. Descends ensuite sur les ailes du nez, puis termine sous les pommettes.',
    }),
    p({
        id: 'gua-sha',
        name: 'Gua sha',
        withArticle: 'le gua sha',
        category: 'soin',
        what: 'Une technique traditionnelle chinoise, aujourd’hui populaire en rituel beauté, qui consiste à lisser la peau à l’aide d’une pierre plate.',
        mantra: 'Je prends le temps de prendre soin de moi.',
        exercise: 'Pas de pierre ? Utilise le plat de tes doigts avec un peu de crème. Lisse ton visage de l’intérieur vers l’extérieur : du menton vers les oreilles, du nez vers les tempes, du front vers la racine des cheveux.',
    }),
    p({
        id: 'do-in',
        name: 'Do-in',
        withArticle: 'le do-in',
        category: 'soin',
        what: 'Une pratique japonaise d’automassage, faite de tapotements, pressions et étirements, pour réveiller le corps en douceur.',
        mantra: 'Je réveille mon corps avec bienveillance.',
        exercise: 'Tapote le sommet de ta tête du bout des doigts, comme une pluie légère. Descends sur la nuque, les épaules, puis tapote tes bras et tes jambes, poings souples. Termine en frottant tes mains et en les posant sur tes yeux.',
    }),
    p({
        id: 'acupression',
        name: 'Acupression',
        withArticle: 'l’acupression',
        category: 'soin',
        what: 'Une technique de pressions des doigts sur des points précis du corps, inspirée de la médecine traditionnelle chinoise.',
        mantra: 'J’appuie sur pause, je respire.',
        exercise: 'Place 3 doigts sous le pli de ton poignet, côté paume : le point se trouve juste sous ton index, entre les deux tendons. Presse-le doucement en faisant de petits cercles pendant 1 minute, puis change de main.',
    }),
    p({
        id: 'osteopathie',
        name: 'Ostéopathie',
        withArticle: 'l’ostéopathie',
        category: 'soin',
        what: 'Une approche manuelle qui s’intéresse à la mobilité du corps dans son ensemble, pratiquée par des professionnels formés à cette discipline.',
        mantra: 'J’écoute mon corps et je lui fais de la place.',
        exercise: 'Assieds-toi le dos droit. Tourne très lentement la tête à droite, reviens, puis à gauche. Incline ensuite l’oreille vers l’épaule, de chaque côté. Des mouvements lents, sans douleur, en respirant.',
    }),
    p({
        id: 'fasciatherapie',
        name: 'Fasciathérapie',
        withArticle: 'la fasciathérapie',
        category: 'soin',
        what: 'Une approche manuelle douce qui s’intéresse aux fascias, ces fines membranes qui enveloppent les muscles et les organes.',
        mantra: 'Je m’ouvre à la douceur du mouvement.',
        exercise: 'Pose tes mains à plat sur ton ventre. Sans appuyer, imagine que tes mains écoutent. Accompagne très lentement le mouvement de ta respiration pendant 3 minutes, avec une attention douce.',
    }),
    p({
        id: 'kinesiologie',
        name: 'Kinésiologie',
        withArticle: 'la kinésiologie',
        category: 'soin',
        what: 'Une approche qui utilise notamment le test musculaire comme outil d’écoute, dans une démarche de mieux-être et de gestion du stress.',
        mantra: 'J’écoute ce que mon corps me dit.',
        exercise: 'Fais les « mouvements croisés » : debout, touche ton genou gauche avec ta main droite, puis ton genou droit avec ta main gauche. Continue lentement 1 minute, puis 1 minute un peu plus vite, en respirant.',
    }),
    p({
        id: 'reiki',
        name: 'Reiki',
        withArticle: 'le reiki',
        category: 'soin',
        what: 'Une pratique d’origine japonaise d’imposition des mains, sans manipulation, vécue par beaucoup comme un moment de profonde détente.',
        mantra: 'J’accueille la paix qui est déjà en moi.',
        exercise: 'Allonge-toi, pose une main sur ton cœur et l’autre sur ton ventre. Sens la chaleur de tes mains. À chaque expiration, imagine qu’une lumière douce se diffuse dans ton corps. Reste ainsi 3 minutes.',
    }),
    p({
        id: 'relaxation-coreenne',
        name: 'Relaxation coréenne',
        withArticle: 'la relaxation coréenne',
        category: 'soin',
        what: 'Une technique de relaxation passive faite de bercements, d’étirements doux et de vibrations, pratiquée au sol en vêtements confortables.',
        mantra: 'Je me laisse bercer.',
        exercise: 'Allonge-toi sur le dos. Laisse tes jambes rouler doucement de droite à gauche, en relâchant les hanches. Fais ensuite de même avec ta tête, tout doucement. Laisse-toi bercer par ce mouvement.',
    }),

    // ───────────── Mouvement ─────────────
    p({
        id: 'hatha-yoga',
        name: 'Hatha yoga',
        withArticle: 'le hatha yoga',
        category: 'mouvement',
        what: 'Le yoga « classique », qui associe postures tenues, respiration et relaxation, accessible à tous les niveaux.',
        mantra: 'Mes racines sont solides, mon cœur est ouvert.',
        exercise: 'Mets-toi en posture de l’enfant : à genoux, fesses sur les talons, front posé au sol ou sur un coussin, bras le long du corps. Respire profondément dans ton dos pendant 3 minutes.',
    }),
    p({
        id: 'yin-yoga',
        name: 'Yin yoga',
        withArticle: 'le yin yoga',
        category: 'mouvement',
        what: 'Un yoga lent et méditatif, où l’on tient des postures au sol plusieurs minutes pour étirer en douceur les tissus profonds.',
        mantra: 'Dans la lenteur, je trouve ma force.',
        exercise: 'Assieds-toi plante des pieds collées, genoux ouverts (posture du papillon). Penche-toi légèrement vers l’avant, sans forcer, et reste 3 minutes en respirant lentement. Glisse des coussins sous tes genoux si besoin.',
    }),
    p({
        id: 'kundalini-yoga',
        name: 'Kundalini yoga',
        withArticle: 'le kundalini yoga',
        category: 'mouvement',
        what: 'Un yoga dynamique qui combine mouvements répétés, respirations, chants et méditation, pour éveiller l’énergie.',
        mantra: 'Je laisse mon énergie s’éveiller.',
        exercise: 'Assieds-toi en tailleur, mains sur les genoux. En inspirant, bascule la poitrine vers l’avant en creusant le dos ; en expirant, arrondis le dos. Continue 2 minutes à ton rythme, puis reste immobile 1 minute.',
    }),
    p({
        id: 'vinyasa-yoga',
        name: 'Vinyasa yoga',
        withArticle: 'le vinyasa yoga',
        category: 'mouvement',
        what: 'Un yoga fluide où les postures s’enchaînent en rythme avec la respiration, comme une danse lente.',
        mantra: 'Je suis le mouvement de mon souffle.',
        exercise: 'À quatre pattes, enchaîne « chat-vache » : inspire en creusant le dos et en levant le regard, expire en arrondissant le dos et en rentrant le menton. Fais 10 cycles lents, un mouvement par respiration.',
    }),
    p({
        id: 'yoga-restauratif',
        name: 'Yoga restauratif',
        withArticle: 'le yoga restauratif',
        category: 'mouvement',
        what: 'Un yoga très doux, où l’on s’installe dans des postures soutenues par des coussins et des couvertures, pour un repos total.',
        mantra: 'Je n’ai rien à faire, juste à être.',
        exercise: 'Allonge-toi sur le dos, les jambes posées contre un mur ou sur une chaise. Pose les mains sur ton ventre, ferme les yeux et reste 3 minutes à respirer tranquillement.',
    }),
    p({
        id: 'qi-gong',
        name: 'Qi gong',
        withArticle: 'le qi gong',
        category: 'mouvement',
        what: 'Une gymnastique douce issue de la tradition chinoise, qui associe mouvements lents, respiration et concentration.',
        mantra: 'Je suis souple comme le bambou.',
        exercise: 'Debout, pieds à la largeur des hanches, genoux légèrement fléchis. En inspirant, monte lentement les bras devant toi jusqu’aux épaules ; en expirant, redescends-les en pliant un peu les genoux. Répète 10 fois.',
    }),
    p({
        id: 'tai-chi',
        name: 'Tai-chi',
        withArticle: 'le tai-chi',
        category: 'mouvement',
        what: 'Un art martial chinois pratiqué au ralenti, en enchaînements fluides, souvent décrit comme une méditation en mouvement.',
        mantra: 'Lentement, je trouve mon centre.',
        exercise: 'Debout, genoux souples, transfère très lentement ton poids sur la jambe droite, puis sur la gauche, comme une vague. Laisse tes bras flotter devant toi et suivre le mouvement. Continue 3 minutes.',
    }),
    p({
        id: 'pilates',
        name: 'Pilates',
        withArticle: 'le Pilates',
        category: 'mouvement',
        what: 'Une méthode de renforcement musculaire douce, centrée sur les muscles profonds, la posture et la respiration.',
        mantra: 'Je me renforce de l’intérieur.',
        exercise: 'Allonge-toi sur le dos, genoux pliés. En expirant, rentre doucement le nombril et décolle le bassin, vertèbre par vertèbre. Inspire en haut, expire en redescendant. Répète 8 fois.',
    }),
    p({
        id: 'feldenkrais',
        name: 'Feldenkrais',
        withArticle: 'la méthode Feldenkrais',
        category: 'mouvement',
        what: 'Une méthode d’éducation somatique qui explore des mouvements lents et doux, pour développer la conscience de soi et la liberté de mouvement.',
        mantra: 'Chaque petit mouvement m’apprend quelque chose.',
        exercise: 'Assieds-toi au bord d’une chaise. Tourne lentement la tête à droite et note jusqu’où tu vas. Puis tourne les yeux à gauche en tournant la tête à droite, 5 fois, très lentement. Refais le premier mouvement : que remarques-tu ?',
    }),
    p({
        id: 'technique-alexander',
        name: 'Technique Alexander',
        withArticle: 'la technique Alexander',
        category: 'mouvement',
        what: 'Une méthode qui aide à prendre conscience de ses habitudes posturales, pour retrouver aisance et légèreté dans les gestes du quotidien.',
        mantra: 'Ma tête s’élève, mon dos s’allonge.',
        exercise: 'Tiens-toi debout, sans forcer. Imagine qu’un fil tire doucement le sommet de ton crâne vers le ciel. Laisse ton cou se libérer et tes épaules s’élargir. Respire 3 minutes en gardant cette image.',
    }),
    p({
        id: 'stretching',
        name: 'Stretching',
        withArticle: 'le stretching',
        category: 'mouvement',
        what: 'Des étirements doux et progressifs, pour délier le corps, gagner en souplesse et relâcher les tensions accumulées.',
        mantra: 'Je fais de la place en moi.',
        exercise: 'Debout, genoux légèrement fléchis, penche-toi lentement en avant en laissant pendre la tête et les bras. Reste 5 respirations, puis remonte vertèbre par vertèbre. Termine en étirant les bras vers le ciel.',
    }),
    p({
        id: 'danse-intuitive',
        name: 'Danse intuitive',
        withArticle: 'la danse intuitive',
        category: 'mouvement',
        what: 'Une danse libre, sans chorégraphie ni jugement, où l’on laisse le corps s’exprimer spontanément sur la musique.',
        mantra: 'Mon corps sait danser ma joie.',
        exercise: 'Choisis une musique qui te touche. Ferme les yeux et laisse ton corps bouger comme il en a envie, même tout doucement. Il n’y a pas de bons ou de mauvais mouvements : seulement les tiens.',
    }),
    p({
        id: 'biodanza',
        name: 'Biodanza',
        withArticle: 'la biodanza',
        category: 'mouvement',
        what: 'Une pratique de danse en groupe, sur des musiques variées, qui met l’accent sur la joie, la vitalité et le lien aux autres.',
        mantra: 'Je célèbre la vie qui danse en moi.',
        exercise: 'Mets une musique joyeuse. Marche dans la pièce en rythme en balançant les bras, puis laisse ta marche se transformer en danse. Souris, même sans raison. 3 minutes de pure vitalité.',
    }),
    p({
        id: 'cinq-rythmes',
        name: 'Danse des 5 rythmes',
        withArticle: 'la danse des 5 rythmes',
        category: 'mouvement',
        what: 'Une pratique de mouvement libre qui traverse cinq énergies : fluide, staccato, chaos, lyrique et immobilité.',
        mantra: 'Je traverse mes vagues intérieures.',
        exercise: 'Sur une musique, bouge 30 secondes de façon fluide et ronde, puis 30 secondes en gestes nets et saccadés, puis 30 secondes en lâchant tout. Ralentis en gestes légers et termine immobile 1 minute.',
    }),
    p({
        id: 'gym-douce',
        name: 'Gym douce',
        withArticle: 'la gym douce',
        category: 'mouvement',
        what: 'Des exercices accessibles à tous, pour entretenir la mobilité, l’équilibre et la tonicité en douceur.',
        mantra: 'Chaque jour, je prends soin de mon corps.',
        exercise: 'Debout, fais 10 rotations lentes des épaules vers l’arrière, 10 rotations des poignets, puis 10 rotations des chevilles de chaque côté. Termine par 10 montées sur la pointe des pieds.',
    }),
    p({
        id: 'yoga-du-visage',
        name: 'Yoga du visage',
        withArticle: 'le yoga du visage',
        category: 'mouvement',
        what: 'Une série d’exercices qui mobilisent et détendent les muscles du visage, souvent pratiquée comme un rituel de détente.',
        mantra: 'Mon visage s’illumine de douceur.',
        exercise: 'Ouvre grand la bouche et les yeux pendant 5 secondes, puis resserre tout ton visage vers le nez. Alterne 5 fois. Termine en massant tes mâchoires en petits cercles et en souriant largement.',
    }),
    p({
        id: 'danse-therapie',
        name: 'Danse-thérapie',
        withArticle: 'la danse-thérapie',
        category: 'mouvement',
        what: 'Une approche qui utilise le mouvement et la danse comme moyens d’expression et d’exploration de soi, accompagnée par un professionnel.',
        mantra: 'Ce que je ne dis pas, mon corps peut le danser.',
        exercise: 'Pense à l’émotion que tu ressens en ce moment. Comment bougerait-elle ? Lente, rapide, lourde, légère ? Laisse ton corps la montrer pendant 2 minutes, puis termine par un mouvement qui te fait du bien.',
    }),

    // ───────────── Nature ─────────────
    p({
        id: 'sylvotherapie',
        name: 'Sylvothérapie',
        withArticle: 'la sylvothérapie',
        category: 'nature',
        what: 'Aussi appelée « bain de forêt », c’est le fait de s’immerger en conscience dans la nature, en éveillant tous ses sens au contact des arbres.',
        mantra: 'Je me reconnecte à l’essentiel, ici et maintenant.',
        exercise: 'Près d’un arbre ou d’une plante, pose ta main sur l’écorce ou sur une feuille. Observe sa texture, ses couleurs, son odeur. Respire lentement en imaginant tes pieds qui prennent racine dans le sol.',
    }),
    p({
        id: 'hortitherapie',
        name: 'Hortithérapie',
        withArticle: 'l’hortithérapie',
        category: 'nature',
        what: 'Une approche qui utilise le jardinage et le contact avec les plantes comme support de mieux-être.',
        mantra: 'Je fais pousser la douceur dans ma vie.',
        exercise: 'Occupe-toi d’une plante : retire une feuille sèche, arrose-la, touche sa terre. Prends 3 minutes pour l’observer comme si tu la voyais pour la première fois.',
    }),
    p({
        id: 'marche-nordique',
        name: 'Marche nordique',
        withArticle: 'la marche nordique',
        category: 'nature',
        what: 'Une marche dynamique avec des bâtons, qui sollicite tout le corps tout en restant douce pour les articulations.',
        mantra: 'J’avance avec énergie et légèreté.',
        exercise: 'Sors marcher 3 minutes d’un bon pas. Balance bien les bras, déroule tes pieds du talon aux orteils et grandis-toi. Sens ton cœur qui accélère un peu et ton souffle qui s’anime.',
    }),
    p({
        id: 'marche-afghane',
        name: 'Marche afghane',
        withArticle: 'la marche afghane',
        category: 'nature',
        what: 'Une technique qui synchronise la respiration avec les pas, pour marcher longtemps avec aisance et dans le calme.',
        mantra: 'Mes pas et mon souffle avancent ensemble.',
        exercise: 'En marchant, inspire sur 3 pas, fais une petite pause sur 1 pas, expire sur 3 pas, puis pause sur 1 pas. Trouve ton rythme sans forcer et continue pendant 3 minutes.',
    }),
    p({
        id: 'grounding',
        name: 'Grounding',
        withArticle: 'le grounding',
        category: 'nature',
        what: 'Aussi appelé « earthing », c’est le fait de marcher pieds nus ou de s’allonger au contact direct de la terre, de l’herbe ou du sable.',
        mantra: 'La terre me porte, je me sens en sécurité.',
        exercise: 'Si tu peux, retire tes chaussures et pose tes pieds nus sur l’herbe, la terre ou le sable. Sinon, pose-les bien à plat sur le sol. Sens chaque point de contact et respire lentement pendant 3 minutes.',
    }),
    p({
        id: 'aromatherapie',
        name: 'Aromathérapie',
        withArticle: 'l’aromathérapie',
        category: 'nature',
        what: 'L’utilisation des huiles essentielles, notamment pour leurs parfums, dans une démarche de bien-être. Elles demandent des précautions d’usage (grossesse, enfants, peau…).',
        mantra: 'Je respire un parfum de sérénité.',
        exercise: 'Sens un parfum que tu aimes : un zeste d’orange, une herbe fraîche, ou une goutte d’huile essentielle sur un mouchoir (jamais pure sur la peau). Inspire lentement, les yeux fermés. Quelles images te viennent ?',
    }),
    p({
        id: 'phytotherapie',
        name: 'Phytothérapie',
        withArticle: 'la phytothérapie',
        category: 'nature',
        what: 'L’usage des plantes sous différentes formes (infusions, extraits…) : une tradition ancienne, à pratiquer avec l’avis d’un professionnel.',
        mantra: 'Je savoure la douceur des plantes.',
        exercise: 'Prépare une infusion que tu aimes (tilleul, verveine, camomille…). Pendant qu’elle infuse, observe la couleur de l’eau qui change. Bois-la lentement, sans écran, en savourant chaque gorgée.',
    }),
    p({
        id: 'fleurs-de-bach',
        name: 'Fleurs de Bach',
        withArticle: 'les fleurs de Bach',
        category: 'nature',
        what: 'Une méthode créée par le Dr Edward Bach, qui associe 38 élixirs floraux à différents états émotionnels.',
        mantra: 'J’accueille mes émotions comme des fleurs qui passent.',
        exercise: 'Prends 3 minutes pour nommer ton émotion du moment, sans la juger : inquiétude, impatience, fatigue, joie… Écris-la. Puis note ce dont tu aurais besoin pour qu’elle s’apaise ou qu’elle grandisse.',
    }),

    // ───────────── Eau ─────────────
    p({
        id: 'thalassotherapie',
        name: 'Thalassothérapie',
        withArticle: 'la thalassothérapie',
        category: 'eau',
        what: 'Des soins qui s’appuient sur le milieu marin : eau de mer, algues, boues marines et climat océanique.',
        mantra: 'Je me laisse porter par l’océan.',
        exercise: 'Ferme les yeux et écoute un enregistrement de vagues. Inspire quand la vague monte, expire quand elle se retire. 3 minutes au bord de la mer, où que tu sois.',
    }),
    p({
        id: 'balneotherapie',
        name: 'Balnéothérapie',
        withArticle: 'la balnéothérapie',
        category: 'eau',
        what: 'Des soins basés sur les bains (eau chaude, bulles, jets), pour un moment de détente et de relâchement musculaire.',
        mantra: 'L’eau emporte mes tensions.',
        exercise: 'Plonge tes mains ou tes pieds dans une bassine d’eau chaude, pas brûlante. Ferme les yeux et concentre-toi sur la sensation de chaleur. Imagine que tes tensions se dissolvent dans l’eau.',
    }),
    p({
        id: 'hammam',
        name: 'Hammam',
        withArticle: 'le hammam',
        category: 'eau',
        what: 'Le bain de vapeur traditionnel du Maghreb et du Moyen-Orient, souvent associé à un gommage, comme un rituel de détente.',
        mantra: 'Je fais peau neuve, en douceur.',
        exercise: 'Sous la douche chaude, prends une minute pour laisser la vapeur t’envelopper. Masse ensuite ta peau avec un gant, en petits cercles, des pieds vers le cœur. Termine par un rinçage tiède.',
    }),
    p({
        id: 'sauna',
        name: 'Sauna',
        withArticle: 'le sauna',
        category: 'eau',
        what: 'Un bain de chaleur sèche d’origine finlandaise, souvent alterné avec des moments de fraîcheur et de repos.',
        mantra: 'Je laisse la chaleur me détendre.',
        exercise: 'Pas de sauna ? Termine ta douche chaude par quelques secondes d’eau tiède, enveloppe-toi dans une serviette et accorde-toi 2 minutes de repos au calme, les yeux fermés, en écoutant ta respiration.',
    }),
    p({
        id: 'methode-kneipp',
        name: 'Méthode Kneipp',
        withArticle: 'la méthode Kneipp',
        category: 'eau',
        what: 'Une approche de bien-être créée au XIXe siècle par Sebastian Kneipp, qui utilise notamment l’eau fraîche pour tonifier le corps.',
        mantra: 'La fraîcheur me réveille et me revitalise.',
        exercise: 'Sous la douche, si tu te sens bien, termine en passant de l’eau fraîche (pas glacée) du pied droit jusqu’au genou, puis à gauche, pendant quelques secondes. Sèche-toi et frotte tes jambes pour les réchauffer.',
    }),
    p({
        id: 'watsu',
        name: 'Watsu',
        withArticle: 'le watsu',
        category: 'eau',
        what: 'Une pratique de relaxation dans une eau chaude, où le praticien berce et étire en douceur la personne qui flotte.',
        mantra: 'Je me laisse flotter, en confiance.',
        exercise: 'Dans ton bain ou sur ton lit, imagine que tu flottes sur une eau tiède. Ton corps est léger, soutenu. Respire lentement et laisse chaque membre se relâcher, l’un après l’autre.',
    }),

    // ───────────── Accompagnement ─────────────
    p({
        id: 'naturopathie',
        name: 'Naturopathie',
        withArticle: 'la naturopathie',
        category: 'accompagnement',
        what: 'Une approche d’hygiène de vie qui s’intéresse à l’alimentation, au sommeil, au mouvement et à la gestion du stress, dans une démarche globale de mieux-être.',
        mantra: 'Je prends soin de moi, simplement et naturellement.',
        exercise: 'Bois lentement un grand verre d’eau tiède. Puis prends 2 minutes pour noter une petite habitude que tu aimerais adopter cette semaine : dormir un peu plus tôt, marcher, cuisiner…',
    }),
    p({
        id: 'hypnose',
        name: 'Hypnose',
        withArticle: 'l’hypnose',
        category: 'accompagnement',
        what: 'Un état de conscience naturel, entre veille et sommeil, utilisé par des praticiens pour accompagner le changement et la détente.',
        mantra: 'Mon esprit connaît déjà le chemin du calme.',
        exercise: 'Fixe un point et respire lentement. Imagine un escalier de 10 marches qui descend vers un lieu calme. Descends-le marche après marche, en te détendant un peu plus à chacune. Puis remonte en douceur.',
    }),
    p({
        id: 'eft',
        name: 'EFT',
        withArticle: 'l’EFT',
        category: 'accompagnement',
        what: 'Une technique qui associe des tapotements sur certains points du visage et du corps à des phrases sur ce que l’on ressent.',
        mantra: 'Même avec cette émotion, je m’accepte pleinement.',
        exercise: 'Pense à un petit tracas. Tapote doucement le tranchant de ta main en disant : « Même si je ressens ça, je m’accepte complètement. » Puis tapote le sommet de ta tête, le début du sourcil et sous l’œil, en respirant.',
    }),
    p({
        id: 'pnl',
        name: 'PNL',
        withArticle: 'la PNL',
        category: 'accompagnement',
        what: 'La programmation neuro-linguistique : un ensemble d’outils de communication et de développement personnel pour mieux comprendre ses façons de penser et d’agir.',
        mantra: 'Je choisis les mots qui me font grandir.',
        exercise: 'Écris une phrase négative que tu te dis souvent (« Je n’y arrive jamais »). Transforme-la en phrase positive et réaliste (« J’apprends pas à pas »). Répète-la 3 fois à voix haute.',
    }),
    p({
        id: 'coaching-de-vie',
        name: 'Coaching de vie',
        withArticle: 'le coaching de vie',
        category: 'accompagnement',
        what: 'Un accompagnement tourné vers l’action, qui aide à clarifier ses objectifs et à avancer vers ce qui compte vraiment.',
        mantra: 'Un petit pas aujourd’hui, un grand chemin demain.',
        exercise: 'Réponds par écrit à ces 3 questions : Qu’est-ce qui compte le plus pour moi en ce moment ? Qu’est-ce qui m’en éloigne ? Quel tout petit pas puis-je faire aujourd’hui ?',
    }),
    p({
        id: 'psychologie-positive',
        name: 'Psychologie positive',
        withArticle: 'la psychologie positive',
        category: 'accompagnement',
        what: 'Une branche de la psychologie qui étudie ce qui contribue au bien-être : les forces, les émotions positives, le sens et les relations.',
        mantra: 'Je nourris ce qui va bien dans ma vie.',
        exercise: 'Note 3 choses qui se sont bien passées récemment, même toutes petites. Pour chacune, écris pourquoi elle a eu lieu et quel rôle tu y as joué.',
    }),
    p({
        id: 'ayurveda',
        name: 'Ayurveda',
        withArticle: 'l’ayurveda',
        category: 'accompagnement',
        what: 'Une tradition indienne millénaire qui s’intéresse à l’équilibre du corps et de l’esprit, à travers l’alimentation, les routines et les soins.',
        mantra: 'Je vis au rythme de ma nature.',
        exercise: 'Crée un mini-rituel : bois un verre d’eau tiède, étire-toi 1 minute, puis masse doucement ton visage et tes oreilles. Trois gestes simples pour prendre soin de toi.',
    }),
    p({
        id: 'mtc',
        name: 'Médecine chinoise',
        withArticle: 'la médecine traditionnelle chinoise',
        category: 'accompagnement',
        what: 'Un ensemble de pratiques traditionnelles chinoises (acupuncture, diététique, massages, qi gong…) fondées sur la notion d’équilibre et de circulation de l’énergie.',
        mantra: 'Je cultive l’équilibre en moi.',
        exercise: 'Frotte tes mains l’une contre l’autre jusqu’à ce qu’elles chauffent, puis pose-les sur tes yeux fermés. Reste ainsi 1 minute. Recommence 3 fois, en respirant doucement.',
    }),
    p({
        id: 'gestalt-therapie',
        name: 'Gestalt-thérapie',
        withArticle: 'la Gestalt-thérapie',
        category: 'accompagnement',
        what: 'Une approche d’accompagnement psychologique centrée sur l’ici et maintenant, la conscience de ce que l’on vit et la relation.',
        mantra: 'Je suis en contact avec ce que je ressens.',
        exercise: 'Complète plusieurs fois cette phrase, à voix haute ou par écrit : « En ce moment, je remarque que… ». Une sensation, une émotion, un son, une pensée. Sans analyser, juste constater.',
    }),
    p({
        id: 'ikigai',
        name: 'Ikigaï',
        withArticle: 'l’ikigaï',
        category: 'accompagnement',
        what: 'Un concept japonais qui désigne sa « raison d’être » : la rencontre entre ce que l’on aime, ce que l’on sait faire et ce qui est utile aux autres.',
        mantra: 'Ce que j’aime faire nourrit ma vie.',
        exercise: 'Trace 3 colonnes : « Ce que j’aime », « Ce que je fais bien », « Ce qui est utile aux autres ». Remplis chacune de 3 idées, puis cherche ce qui revient dans plusieurs colonnes.',
    }),

    // ───────────── Cocon & créativité ─────────────
    p({
        id: 'art-therapie',
        name: 'Art-thérapie',
        withArticle: 'l’art-thérapie',
        category: 'cocon',
        what: 'Une approche qui utilise la création artistique (dessin, peinture, modelage…) comme moyen d’expression et de mieux-être, accompagnée par un professionnel.',
        mantra: 'Je crée sans juger, je m’exprime librement.',
        exercise: 'Prends une feuille et des crayons. Sans réfléchir, dessine des formes et des couleurs qui représentent ton humeur du moment. Aucun talent requis : seulement le plaisir du geste.',
    }),
    p({
        id: 'musicotherapie',
        name: 'Musicothérapie',
        withArticle: 'la musicothérapie',
        category: 'cocon',
        what: 'Une approche qui utilise la musique et le son, en écoute ou en pratique, pour accompagner le bien-être émotionnel.',
        mantra: 'La musique accorde mon cœur.',
        exercise: 'Choisis un morceau calme et écoute-le les yeux fermés, en entier. Essaie de suivre un seul instrument du début à la fin. Remarque ce que la musique change en toi.',
    }),
    p({
        id: 'journaling',
        name: 'Journaling',
        withArticle: 'le journaling',
        category: 'cocon',
        what: 'L’écriture régulière de ses pensées, émotions et intentions dans un carnet, pour y voir plus clair et prendre du recul.',
        mantra: 'En écrivant, je fais de la place en moi.',
        exercise: 'Prends un carnet et écris sans t’arrêter pendant 3 minutes, en commençant par « Aujourd’hui, je me sens… ». Ne corrige rien, ne relis pas : laisse simplement couler les mots.',
    }),
    p({
        id: 'mandala',
        name: 'Mandala',
        withArticle: 'le mandala',
        category: 'cocon',
        what: 'Un dessin circulaire aux motifs symétriques, dont le coloriage ou la création favorise la concentration et le calme.',
        mantra: 'Je reviens à mon centre, calmement.',
        exercise: 'Dessine un petit cercle au centre d’une feuille, puis des cercles de plus en plus grands autour. Remplis chaque anneau de motifs simples qui se répètent : points, pétales, vagues. Laisse ta main ralentir.',
    }),
    p({
        id: 'alimentation-consciente',
        name: 'Alimentation consciente',
        withArticle: 'l’alimentation consciente',
        category: 'cocon',
        what: 'Aussi appelée « mindful eating », c’est l’art de manger en pleine présence, en savourant chaque bouchée et en écoutant ses sensations.',
        mantra: 'Je savoure, je remercie, je me nourris.',
        exercise: 'Prends un aliment simple (un fruit, un carré de chocolat). Observe-le, sens-le, puis mets-le en bouche sans croquer. Laisse les saveurs se révéler, puis mâche très lentement.',
    }),
    p({
        id: 'micro-sieste',
        name: 'Micro-sieste',
        withArticle: 'la micro-sieste',
        category: 'cocon',
        what: 'Un court moment de repos de 5 à 20 minutes dans la journée, pour recharger ses batteries sans perturber le sommeil de la nuit.',
        mantra: 'Me reposer, c’est aussi avancer.',
        exercise: 'Installe-toi confortablement, règle un minuteur sur 3 à 10 minutes et ferme les yeux. Pas besoin de dormir : laisse simplement ton corps se relâcher et ta respiration ralentir.',
    }),
    p({
        id: 'feng-shui',
        name: 'Feng shui',
        withArticle: 'le feng shui',
        category: 'cocon',
        what: 'Un art chinois ancien d’aménagement de l’espace, qui cherche à créer des lieux harmonieux où l’énergie circule bien.',
        mantra: 'Mon espace respire, moi aussi.',
        exercise: 'Regarde la pièce où tu es. Déplace ou range un seul objet pour libérer un passage ou dégager une surface. Puis ouvre la fenêtre 3 minutes pour renouveler l’air.',
    }),
    p({
        id: 'desencombrement',
        name: 'Désencombrement',
        withArticle: 'le désencombrement',
        category: 'cocon',
        what: 'Une démarche qui consiste à trier et alléger son intérieur pour ne garder que ce qui est utile ou qui fait du bien.',
        mantra: 'Je garde ce qui compte, je laisse partir le reste.',
        exercise: 'Choisis une toute petite zone : un tiroir, ton sac ou l’écran d’accueil de ton téléphone. En 3 minutes, retire tout ce qui est inutile. Admire le résultat et savoure cette légèreté.',
    }),
    p({
        id: 'gratitude',
        name: 'Gratitude',
        withArticle: 'la gratitude',
        category: 'cocon',
        what: 'Une pratique qui consiste à remarquer et apprécier volontairement les bonnes choses de sa vie, grandes ou petites.',
        mantra: 'Merci pour tout ce qui est déjà là.',
        exercise: 'Écris 3 mercis d’aujourd’hui : une personne, un moment, une chose simple. Pour chacun, prends le temps de revivre le souvenir et de ressentir la gratitude.',
    }),
    p({
        id: 'bibliotherapie',
        name: 'Bibliothérapie',
        withArticle: 'la bibliothérapie',
        category: 'cocon',
        what: 'L’utilisation de la lecture comme source de réconfort, d’inspiration et de réflexion sur soi.',
        mantra: 'Les mots m’ouvrent de nouveaux chemins.',
        exercise: 'Ouvre au hasard un livre qui t’inspire et lis une page lentement. Recopie une phrase qui te touche et garde-la avec toi aujourd’hui.',
    }),
    p({
        id: 'hygge',
        name: 'Hygge',
        withArticle: 'le hygge',
        category: 'cocon',
        what: 'Un art de vivre danois qui célèbre les petits plaisirs, le confort et les moments chaleureux partagés.',
        mantra: 'Je crée de la douceur autour de moi.',
        exercise: 'Crée ton coin douillet : un plaid, une lumière tamisée, une boisson chaude. Installe-toi 3 minutes, sans écran, et savoure simplement ce moment de confort.',
    }),
    p({
        id: 'luminotherapie',
        name: 'Luminothérapie',
        withArticle: 'la luminothérapie',
        category: 'cocon',
        what: 'L’exposition à une lumière vive, proche de celle du jour, souvent utilisée pendant les mois sombres pour retrouver de l’entrain.',
        mantra: 'Je laisse entrer la lumière.',
        exercise: 'Va près d’une fenêtre ou sors quelques minutes à la lumière du jour. Ferme les yeux, tourne ton visage vers le ciel (sans fixer le soleil) et respire profondément pendant 3 minutes.',
    }),
    p({
        id: 'chant-libre',
        name: 'Chant libre',
        withArticle: 'le chant libre',
        category: 'cocon',
        what: 'Chanter pour le plaisir, sans objectif de performance : une façon simple de libérer sa voix, son souffle et ses émotions.',
        mantra: 'Ma voix a le droit d’exister.',
        exercise: 'Fredonne un son grave, bouche fermée (« mmmm »), pendant toute une expiration. Sens la vibration dans ta poitrine et ton visage. Recommence 5 fois, puis chante une chanson que tu aimes.',
    }),

    // ───────────── Lien aux autres ─────────────
    p({
        id: 'yoga-du-rire',
        name: 'Yoga du rire',
        withArticle: 'le yoga du rire',
        category: 'lien',
        what: 'Une pratique qui associe exercices de rire volontaire et respiration, souvent en groupe, pour cultiver la bonne humeur.',
        mantra: 'Je laisse la joie circuler en moi.',
        exercise: 'Commence par sourire largement pendant 30 secondes. Puis fais « ho ho, ha ha ha » en tapant dans tes mains. Force un peu le rire au début… souvent, le vrai rire finit par arriver !',
    }),
    p({
        id: 'cnv',
        name: 'Communication non violente',
        withArticle: 'la communication non violente',
        category: 'lien',
        what: 'Une méthode de communication créée par Marshall Rosenberg, fondée sur l’écoute de ses sentiments et de ses besoins, et de ceux des autres.',
        mantra: 'J’écoute mes besoins et ceux des autres avec bienveillance.',
        exercise: 'Pense à une petite tension récente. Décris-la en 4 temps : ce qui s’est passé (les faits), ce que tu as ressenti, ce dont tu avais besoin, et ce que tu pourrais demander.',
    }),
    p({
        id: 'mediation-animale',
        name: 'Médiation animale',
        withArticle: 'la médiation animale',
        category: 'lien',
        what: 'Une approche qui fait intervenir un animal (chien, cheval…) aux côtés d’un professionnel, pour favoriser le bien-être et le lien.',
        mantra: 'Je m’ouvre à une présence simple et bienveillante.',
        exercise: 'Si tu as un animal, prends 3 minutes pour le caresser lentement en observant sa respiration. Sinon, regarde les oiseaux par la fenêtre ou une vidéo d’animaux qui t’apaise.',
    }),
    p({
        id: 'improvisation',
        name: 'Improvisation théâtrale',
        withArticle: 'l’improvisation théâtrale',
        category: 'lien',
        what: 'Une pratique de théâtre sans texte, où l’on invente en direct, qui développe la confiance, l’écoute et la spontanéité.',
        mantra: 'J’accueille l’imprévu avec légèreté.',
        exercise: 'Prends un objet autour de toi et invente-lui 3 nouvelles utilisations complètement farfelues, à voix haute. Joue le jeu à fond : le but est de t’amuser, pas de bien faire.',
    }),
];
